name: RELEASE CI/CD
run-name: RELEASE CI/CD

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release Type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major


jobs:
  pre-commit:
    uses: ./.github/workflows/pre_commit.yaml

  test:
    uses: ./.github/workflows/test.yaml

  bump:
    needs: [pre-commit, test]
    uses: ./.github/workflows/bump.yaml
    with:
      release_type: ${{ inputs.release_type }}
    secrets: inherit
